project:
  type: website
  output-dir: docs

website:
  title: "Stanisław Mazur"

  navbar:
    background: "#ffffff"
    foreground: "#243247"
    pinned: true
    search: false
    right:
      - text: "Home"
        href: index.qmd
      #- text: "Publications"
        #href: publications.qmd
      #- text: "CV"
        #href: cv.pdf

  page-footer:
    center: "© 2026 Stanisław Mazur"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false